### DISCUSSION TITLE
기능 건의

### DISCUSSION THREAD

**Discussion by wooooooooooook** [eigger/espcomponents#137] [Ideas]
안녕하세요.
혹시나 가능한 기능인지 문의드립니다.
삼성SDS월패드에서 엘리베이터 호출을 위해서는 현관스위치(엘베호출버튼)를 탈거하고 
월패드에서 보내는 상태확인패킷에 현관스위치 대신 특정패킷으로 응답을 해줌으로 가능해집니다.
그래서 이런 기능이 가능할지 의견 드립니다.

 - 특정 패킷 수신시 조건부로 응답패킷을 보내는기능
예를들어 uartex.send_command로 원하는 패킷을 전송할수 있다고 한다면

```
uartex:
   response_rules:
    - trigger: 0xCC5A010017
      response:
            uartex.send_command(0xB05A01006B)
    - trigger: 0xCC4101000C
      response:
        if:
          condition:
            switch.is_on: my_switch
          then:
            uartex.send_command(0xB010010120)
          else:
            uartex.send_command(0xB041010070)
```

이런식으로 사전 정의된 패킷이 수신되었을때 즉시 특정 패킷을 송신, 혹은 조건에 따라 송신하도록 하는 기능이 구현된다면 SDS에서 엘베호출, 가스잠금 등의 기능 구현이 가능해질 것 같습니다.

**Comment by wooooooooooook** [comment]
추가로 주기적 패킷 송신기능이 있으면 월패드 대체까지도 가능할 것같습니다.

```
uartex:
  periodic_command:
    interval: 100ms
    commands: [0xCC5A010017, 0xAD41006C]
```
