### DISCUSSION TITLE
Climate 기능 개선

### DISCUSSION THREAD

**Discussion by wooooooooooook** [eigger/espcomponents#138] [Ideas]
수정해서 PR날려보려했으나 실력 부족으로 건의만 드립니다.
https://developers.home-assistant.io/docs/core/entity/climate/
climate에서 hvac_action 파라미터 추가가 가능할지 문의드립니다. 
이유는 보일러를 희망온도 15도로 설정하여 OFF 대신 사용하고 있는데, idle상태임에도 HA에서 아이콘이 주황색으로 뜨겁게 표시되기 때문입니다.
hvac_action을 지원하는 경우 idle상태일때는 회색 아이콘으로 표시됩니다.

hvac_action은 idle, heating, cooling만 가능한 것으로 압니다.

만약 가능하다면 commax에서 climate 패킷은 다음과 같습니다.
|offset1 값 | 00 | 81 | 83 |
|---|---|---|---|
|MODE|off|HEAT|HEAT|
|hvac_action|idle|idle|heating|

```
climate:
  - platform: uartex
    ...
    state_hvac_action_idle:
      offset: 1
      data: [0x83]
      inverted: True
    state_hvac_action_heating:
      offset: 1
      data: [0x83]
```

**Comment by wooooooooooook** [comment]
아울러 
위에 언급한바와 같이 commax에서는 heat 모드 변경 명령을 내렸을때, 현재온도가 목표온도보다 낮다면 83(heating)으로 ack를 보낼 수 있습니다.
81, 83모두 ack로 처리할 방안이 있을까요?
```
    command_heat:
      data: [0x04, 0x01, 0x04, 0x81, 0x00, 0x00, 0x00]
      ack: [0x84, 0x81, 0x01]
```

**Comment by eigger** [comment]
action은 한번 추가해 볼게요

ack는 81, 83을 구분 할순 없지만 마스크를 넣어서 처리 할수 있습니다.
```
    command_heat:
      data: [0x04, 0x01, 0x04, 0x81, 0x00, 0x00, 0x00]
      ack: [0x84, 0x80, 0x01]
      mask: [0xFF, 0xF0, 0xFF]
```
or
```
    command_heat:
      data: [0x04, 0x01, 0x04, 0x81, 0x00, 0x00, 0x00]
      ack: [0x84, 0x81, 0x01]
      mask: [0xFF, 0xFD, 0xFF]
```

**Reply by wooooooooooook** [reply]
감사합니다!

**Comment by eigger** [comment]
Dev버전에 올렸는데 테스트 한번 해보실래요? 

```
external_components:
  - source: github://eigger/espcomponents@dev
climate:
  - platform: uartex
    ...
    state_action_idle:
      offset: 1
      data: [0x81]
    state_action_heating:
      offset: 1
      data: [0x83]
```
mode off, heat는 모두 등록은 하셔야 하고
mode off시 action도 off가 되게 일단 해놨습니다.
패킷은 mode가 우선 적용되고 action 패킷이 있으면 추가로 반영 하게 해놨습니다.
