### DISCUSSION TITLE
로그 필터링

### DISCUSSION THREAD

**Discussion by eigger** [eigger/espcomponents#150] [General]
```yaml
text_sensor:
  - platform: uartex
    name: "Filter Log"
    state: 
      data: [0x20, 0x01, 0x11]
    lambda: |-
      return to_hex_string(data, len);
```

헤더 0xF7 이후로 시작 되는 
0x20 0x01 0x11의 패킷만 분류해서 로그로 출력 

즉 0xF7 0x20 0x01 0x11 ... 식으로 처음 패킷이 일치 하는 모든 패킷을 filter log에 출력

**Comment by eigger** [comment]
엘베 필터링 아래 넣고 엘베 버튼 눌러보세요
```yaml
text_sensor:
  - platform: uartex
    name: "Filter Log"
    state: 
      data: [0x20, 0x01, 0x00, 0x81]
      mask: [0xFF, 0xFF, 0x00, 0xFF]
    lambda: |-
      return to_hex_string(data, len);
```

**Comment by eigger** [comment]
엘리베이터 호출 테스트

```yaml
button:
  - platform: uartex
    name: "Elevator Call"
    icon: "mdi:elevator"
    command_on: 
      data: [0x20, 0x01, 0x81, 0x81, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
```
or
```yaml
button:
  - platform: uartex
    name: "Elevator Call"
    icon: "mdi:elevator"
    command_on: 
      data: [0x20, 0x01, 0x81, 0x81, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
```

**Comment by eigger** [comment]
```yaml
- platform: uartex
  id: elevator_floors3
  name: "Elevator Floors3"
  icon: "mdi:elevator"
  state: [0x20, 0x01, 0x22, 0x81]
  state_number: !lambda |-
    uint16_t raw = (data[4] << 8) + data[5];
    int tens = (raw & 0x0100) ? 10 : 0;
    int ones = raw & 0x000F;
    return tens + ones;
```
