### DISCUSSION TITLE
전등 갯수 조절

### DISCUSSION THREAD

**Discussion by eigger** [eigger/espcomponents#158] [General]
1. 전등 갯수
```yaml
  - platform: uartex
    name: "Room 4 Light"
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x04]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 8
      data: [0xff]
    state_off:
      offset: 8
      data: [0x00]
    command_on:
      data: [0x30, 0xbc, 0x00, 0x0e, 0x04, 0x01, 0x00, 0x00, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc]
    command_off:
      data: [0x30, 0xbc, 0x00, 0x0e, 0x04, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc]

```

2. 개별 영역
기기 설정에서 개별 위치 변경
![image](https://github.com/user-attachments/assets/2d508e13-6a7e-48d2-ad8e-df3e79a16706)

3. 엘베 층수
저희집도 패킷이 없어서 그냥 이렇게 사용중입니다.
```yaml
text_sensor:
  - platform: uartex
    name: "Elevator"
    icon: "mdi:elevator"
    state: 
      data: [0x30, 0x00, 0x00, 0x01, 0x00, 0x44, 0x00]
      mask: [0xff, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff]
    lambda: |-
      if (check_value(8, 0x00, data, len)) return "호출";
      if (check_value(8, 0x03, data, len)) return "도착";
      return "Unknown";
```
