### ISSUE TITLE
Feature request : option to use a length of data byte in data to terminate read

### ISSUE THREAD

**Issue by matwho** [eigger/espcomponents#73]
At the moment the read is terminated when either a footer match, a crc match or a time out.

An additional method that would be helpful would be based on a value within the data read back. I this example the 4th byte gives the message length including the crc byte.

```
CAFD062F900166000000000000000001230123012A018501850185000001070C012415361F02BB0000500000308058 (47 bytes)
```

So it goes like this:

```
1  Constant start byte - Header 1
2  Constant start byte - Header 2
3 Address of device returning data - Header 3
4 Length of data including header and CRC byte - not part of header
5 ACK of command used to produce data - Header 4
... data ...
47 CRC
```

I think this approach is quite common. It would be very nice if your component could support this. How about:
```
uartex:
  rx_length_at: 4
```
There is a second issue raised with this data block. The header is not continuous, it would be helpful to include a wild card or mask for the header check definition. Some thing like this:
```
uartex:
  rx_header: [0xCA, 0xFD, 0x06, 0x2F, 0x90]
  rx_header_mask: [0xFF, 0xFF, 0xFF, 0x00, 0xFF]
```
would work nicely!

Your component is going to be so useful!!

**Comment by eigger** [comment]
Thank you for your input. I will consider the header mask function and the feature that references the length of the received data. While implementing the feature is possible, i will further evaluate whether parsing can be sufficiently achieved using the checksum. But if your header changes, wouldn’t using only CAFD as the header be sufficient?

**Comment by matwho** [comment]
Yes it is only ment to be a helpful suggestion, thanks for considering it!

The CA FD header is returned with all types of data blocks, but only the 5th byte tells us if it is the data type we require. The device send of lots of different types of messages its only the 5th byte that tells us if it is the one we are interested in. So in our case using just the CA CF header would let data blocks in with a completely different layout and it would mess everything up.

**Comment by eigger** [comment]
I think I need to provide a more detailed explanation of my component. The uartex configuration is a representative setting that handles all received data, while the actual required data is further filtered at the sensor level.

like this
```
uartex:
  rx_header: [0xCA, 0xFD]

sensor:
  - platform: uartex
    name: Sensor1
    state: 
      data: [0x06, 0x00, 0x90]
      mask: [0xFF, 0x00, 0xFF]

```

**Comment by matwho** [comment]
Yes I agree a better description is needed - maybe I can help write the full documentation for you as a way of helping!

Can you explain how this works asI have missed this!

I have a big block of data that has lots of integers, bytes and bits packed in to it. 

This is how I have set it up at the moment:

```
uartex:
  rx_timeout: 150ms
  tx_delay: 10ms
  tx_timeout: 10ms
  tx_retry_cnt: 3
  rx_header: [0xCA, 0xFD, 0x06, 0x2F, 0x90]
  rx_checksum: !lambda |-
      uint32_t crc = 0xCA + 0xFD + 0x06 + 0x2F + 0x90;
      for (int i = 0; i < len; i++)
      {
        crc += data[i];
      }
      ESP_LOGD("CRC END","%#x",crc & 0x00FF);
      return crc & 0x00FF;
```
then lots of sensors like this:
```
sensor:
  - platform: uartex
    name: "Local Input Voltage"
    unit_of_measurement: "V"
    icon: "mdi:car-battery"
    device_class: "voltage"
    state_class: "measurement"
    state:
      data: [0x00]        # Read All
      mask: [0x00]
    state_number:
      offset: 0
      length: 2
      precision: 0
    filters:
      - multiply: 0.0354838709677419
    accuracy_decimals: 2
  - platform: uartex
    name: "Float Voltage"
    unit_of_measurement: "V"
    icon: "mdi:car-battery"
    device_class: "voltage"
    state_class: "measurement"
    state:
      data: [0x00]        # Read All
      mask: [0x00]
    state_number:
      offset: 18
      length: 2
      precision: 0
    filters:
      - multiply: 0.0354838709677419
    accuracy_decimals: 2

binary_sensor:
  - platform: uartex
    name: "Protection"
    state:
      data: [0x00]        # Read All
      mask: [0x00]
    state_on:
      offset: 35
      data: [0b00000001]
      mask: [0b00000001]
    state_off:
      offset: 35
      data: [0b00000000]
      mask: [0b00000001]

  - platform: uartex
    name: "Input Under 9V"
    state:
      data: [0x00]        # Read All
      mask: [0x00]
    state_on:
      offset: 35
      data: [0b00000010]
      mask: [0b00000010]
    state_off:
      offset: 35
      data: [0b00000000]
      mask: [0b00000010]
```

So are you saying I should do this instead:

```
...
uartex:
  rx_header: [0xCA, 0xFD]
...

sensor:
  - platform: uartex
    name: "Local Input Voltage"
    unit_of_measurement: "V"
    icon: "mdi:car-battery"
    device_class: "voltage"
    state_class: "measurement"
    state: 
      data: [0x06, 0x00, 0x90]
      mask: [0xFF, 0x00, 0xFF]
    state_number:
      offset: 0
      length: 2
      precision: 0
    filters:
      - multiply: 0.0354838709677419
    accuracy_decimals: 2

...

binary_sensor:
  - platform: uartex
    name: "Protection"
    state: 
      data: [0x06, 0x00, 0x90]
      mask: [0xFF, 0x00, 0xFF]
    state_on:
      offset: 35
      data: [0b00000001]
      mask: [0b00000001]
    state_off:
      offset: 35
      data: [0b00000000]
      mask: [0b00000001]
```

So am I correct in my new understanding.

1) When a steam of data arrives and it matches the `rx_header` your component starts reading the data in to a buffer. 

2) It calculates the crc then tries a match or  matches on `rx_footer `or times out. At which point it stops blocking the CPU and lets it run again.

3) Then the sensor `platform: uartex` looks at the data in the buffer and looks for a match (with the mask) and if it finds one it processes the buffer, leaving it intact for any other sensors to operate on.

Question: Not sure if it matches on any bytes in buffer or just the first ones.  

4) It will refresh the buffer with new data if another data stream arrives which matches the `rx_header`.

**Comment by eigger** [comment]
1. Your understanding is correct.
2. If the received packet passes the checksum or matches the footer, the packet is used.
If neither the checksum nor the footer matches, or if both are missing, a timeout error occurs after rx_timeout.
Blocking is maintained.
3. The packet is circulated through all sensors registered in the platform: uartex, checking if it matches a state packet.
Only packets registered in the state are used by the respective sensor.
Once the entire circulation is complete, blocking is released.
4. Your understanding is correct.

For reference, the index of the packet received by the sensor starts from the part excluding the header.
If the header changes, the sensor's offset must be adjusted.
```
0xCA,    0xFD,    0x06, 0x00, 0x90 ...
header, header,     0,    1,    2       <- offset
```

**Comment by matwho** [comment]
OK great this is making more sense, just want to check my understanding on one more thing:

The state packet check - it only looks at the first bytes of the data just after the header?

So its like this:

for:
```
uartex:
  rx_header: [0xCA, 0xFD]
sensor:
  - platform: uartex
    state: 
      data: [0x06, 0x00, 0x90]
      mask: [0xFF, 0x00, 0xFF]
      ...
```
```

0xCA Header
0xFD Header
0x06 State Mask then Check Byte 0x60 Offset =0
0x00 State Mask then Check Byte  0x00  Offset =1
0x90  State Mask then Check Byte  0x90  Offset =2
0x?? Data Offset=3
...

```

Will it find the state bytes if they are further in to the data block?

**Comment by matwho** [comment]
OK thanks that is now clear. I will add this to some documentation just give me a few days, I am really busy at the moment!

**Comment by eigger** [comment]
Thank you for your suggestion. I plan to improve it in the following way. 

1. I will add a mask to the header and include the related options as sub-options.
``` 
rx_header: [0xCA, 0xFD, 0x06, 0x00, 0x90]    
    or  
rx_header:
    data: [0xCA, 0xFD, 0x06, 0x00, 0x90]
    mask: [0xFF, 0xFF, 0xFF, 0x00, 0xFF]

```

2. I will modify it so that it works even without the state packet.

3. I will modify the sensor to support unsigned values. However, instead of using Python syntax, I plan to add an option. While Python syntax is very intuitive for those familiar with it, it can be difficult to understand for those who are not.
```
  state_number:
    offset: 14
    length: 2
    precision: 0
    signed: false

```
