### ISSUE TITLE
Does uartex have any plans to support a media player?

### ISSUE THREAD

**Issue by kylin7226** [eigger/espcomponents#84]
Does uartex have any plans to support a media player?

**Comment by eigger** [comment]
Do you want to send commands like play or stop to the media player via UART? Or do you want to check the media player's status through UART?
I haven't reviewed it so far, but if possible, I'll try to add the feature.

**Comment by eigger** [comment]
You can test it on the dev branch like this.
```
external_components:
  - source: github://eigger/espcomponents@dev
    components: [ uartex ]
    refresh: always

media_player:
  - platform: uartex
    name: "Media"
    state: 
      data: [0xA0, 0x00, 0x01]
      mask: [0xF0, 0x00, 0xFF]
    state_playing:
      offset: 1
      data: [0x01]
    state_idle:
      offset: 1
      data: [0x00]
    state_paused:
      offset: 1
      data: [0x02]
    command_play: 
      data: [0x01]
    command_stop:
      data: [0x02]
    command_pause:
      data: [0x03]
    command_mute:
      data: [0x04]
    command_unmute:
      data: [0x05]
    command_volume: !lambda |-
      return {{0x0D, (uint8_t)x}};
```
